export const SET_MINIMIZE_MENU = "SET_MINIMIZE_MENU"
export const SET_HOVER_STATE = "SET_HOVER_STATE"


export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"
export const SET_DATA_FOR_MODAL = "SET_DATA_FOR_MODAL"


                /*PASSPORT DATA*/
export const PASSPORT_DATA_LOADED = 'PASSPORT_DATA_LOADED'
export const EDIT_DATA = 'EDIT_DATA'

            /* FILTER TYPES */
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY"
export const SET_NEXT_ELEMENTS = "SET_NEXT_ELEMENTS"
export const SET_PREV_ELEMENTS = "SET_PREV_ELEMENTS"
export const SET_LIMIT = "SET_LIMIT"

            /* BOOKS TYPES */
export const GET_BOOKS_START = "GET_BOOKS_START"
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS"
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE"

export const GET_SEARCH_BOOKS_START = "GET_SEARCH_BOOKS_START"
export const GET_SEARCH_BOOKS_SUCCESS = "GET_SEARCH_BOOKS_SUCCESS"
export const GET_SEARCH_BOOKS_FAILURE = "GET_SEARCH_BOOKS_FAILURE"

export const ADD_BOOK_START = "ADD_BOOK_START"
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS"
export const ADD_BOOK_FAILURE = "ADD_BOOK_FAILURE"


export const OPEN_FAVORITE_MODAL = "OPEN_FAVORITE_MODAL"
export const CLOSE_FAVORITE_MODAL = "CLOSE_FAVORITE_MODAL"

export const ADD_BOOK_TO_FAVORITE_START = "ADD_BOOK_TO_FAVORITE_START"
export const ADD_BOOK_TO_FAVORITE_SUCCESS = "ADD_BOOK_TO_FAVORITE_SUCCESS"
export const ADD_BOOK_TO_FAVORITE_FAILURE = "ADD_BOOK_TO_FAVORITE_FAILURE"
export const SELECT_BOOK = "SELECT_BOOK"
export const SET_UPLOAD_PROGRESS = "SET_UPLOAD_PROGRESS"



                                    /* CONTEXT_MENU TYPES */
export const SHOW_MODAL = "SHOW_MODAL"
export const HIDE_MODAL = "HIDE_MODAL"
export const CREATE_BULIM = "CREATE_BULIM"
export const CREATE_INLINE_BULIM = "CREATE_INLINE_BULIM"
export const FETCH_BULIMLAR_START = "FETCH_BULIMLAR_START"
export const FETCH_BULIMLAR_SUCCESS = "FETCH_BULIMLAR_SUCCESS"
export const FETCH_BULIMLAR_FAILURE = "FETCH_BULIMLAR_FAILURE"
                            